# Generated by Django 3.1.1 on 2020-09-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=18)),
                ('keyword', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
    ]
