# Generated by Django 3.1.1 on 2020-09-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('keyword', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('region_2', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=5)),
                ('topic_rate', models.CharField(max_length=20)),
                ('topic_list', models.CharField(max_length=50)),
            ],
        ),
    ]
