# Generated by Django 3.1.1 on 2020-09-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.CharField(max_length=15),
        ),
    ]
